import "./globals.css";
import { Geologica, Lexend_Deca } from "next/font/google";
import { Nav } from "@/app/nav";

// body font
const geologica = Geologica({ subsets: ["latin"] });
// header font
const lexend_deca = Lexend_Deca({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={lexend_deca.className}>
        {/* <Nav /> */}
        {children}
      </body>
    </html>
  );
}
